# Generated by Django 3.2.8 on 2022-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyapi', '0002_auto_20220507_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='toy_item',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
